spring:
  datasource:
    url: jdbc:postgresql://192.168.100.108:5432/rag
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      base-url: http://127.0.0.1:1234
      api-key: lm-studio
      chat:
        options:
          model: openai/gpt-oss-20b
          temperature: 0.2
          max-tokens: -1
      embedding:
        options:
          model: text-embedding-bge-m3
          dim: 1024
          batchSize: 700
          requestTimeout: 120000


rag:
  search:
    default-k: 6
    default-alpha: 0.7
    default-per-doc: 2
  citation:
    preview-length: 180

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.jdbc.core: DEBUG